### ISSUE TITLE
RSS-länk inklistrad i Pocket Casts - inget content spelas upp. 

### ISSUE THREAD

**Issue by Jens-Johansson** [Hanifb/medlem.io#11]
Registrerade mig på dator/ desktop pga skäl.   [pcast:// - länken vill bli hanterad av itunes av någon anledning]

Klistrade in 
 https://medlem.io/rss/<64 siffror hex>

i Pocket Casts.

Podden komer upp som den bör. Men

Trycker på play -- inget händer. Det verkar som filerna i ` <enclosure></enclosure>` inte existerar. 
 
 Verkar snabbt och responsivt annars utan en massa onödigt fluff.

**Comment by Jens-Johansson** [comment]
Det är vissa av objekten bara nu. (Jag kollade iofs inte så många innan)

https://objects.dc-sto1.glesys.net/cold-bar/e/6fEhYhglbj1VU_Y2H0kEHT1a.mp3
https://objects.dc-sto1.glesys.net/cold-bar/e/e6BalonuVNYrQdY3rJhq5O11.mp3
https://objects.dc-sto1.glesys.net/cold-bar/e/cNVLohMo8T4BlchRyB983nsF.mp3
https://objects.dc-sto1.glesys.net/cold-bar/e/UYHzMHTcbm8d1c8yCg7dbzUx.mp3
```
<Error>
<Code>AccessDenied</Code>
<BucketName>cold-bar</BucketName>
<RequestId>tx0000096000227dd1d7cf7-00674e0be8-9e977be-default</RequestId>
<HostId>9e977be-default-default</HostId>
</Error>
```


https://objects.dc-sto1.glesys.net/cold-bar/e/7ssuYkaG4P4ZQJaqqyLGe_TM.mp3
**Fungerar!**


Detta kan ju vara förvirrande för nån som testar

**Comment by Hanifb** [comment]
Hmm, måste blivit fel i rssimport, jag har byggt om hela filsystemet nu och det ska vara fixat. Du får gärna prova igen och se om det har löst sig.

**Comment by Jens-Johansson** [comment]
Jag tror det har löst sig nu om jag fattar det rätt.

Och jag tror fan ta mig att en extra komplikation nu i stället är att Pocketcast cachear den gamla versionen. Om jag klistrar in rss-url:en i Pocket Casts' sökruta får jag nämligen upp en lista med avsnitt som inkluderar avsnittet "test" från 6 december. Trots att jag inte på något sätt är "subscribed" i Pocket Casts verkar RSS-feedsen ändå cachas av dem.

https://medlem.io/rss/<64 siffror hex> bara i en ny tab på chrome verkar rätt.

**Comment by Jens-Johansson** [comment]
Förresten lyssna inte på Per, släpp inte lös plattformen innan allt är klart. Låter störigt med arga kunder parallellt med julstök. Det är ett generellt ofog att släppa saker nuförtiden som inte är hundra. Och som Shigeru Miyamoto lär ska ha sagt:

"A delayed game is eventually good, but a rushed game is forever bad"

**Comment by Hanifb** [comment]
@Jens-Johansson : Håller med. Men nu är det för sent! Fixade länkarna.
