### ISSUE TITLE
Paginera avsnitten?

### ISSUE THREAD

**Issue by sibe7691** [Hanifb/medlem.io#16]
Blir en väldigt lång lista på avsnitt. Paginera innehållet och kanske sökfunktion så ni kan referera till avsnitt i podden sen? 

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/d6e8e3d2-0a96-456d-ab4d-0c3e7d5d2317">

**Comment by Hanifb** [comment]
Fixat!
