### ISSUE TITLE
Ingen möjlighet att lägga till ett kort innan man prenumererat på nåt

### ISSUE THREAD

**Issue by Jens-Johansson** [Hanifb/medlem.io#21]
Vet ej om detta är feature eller bugg. Det kanske är svårt att aktivera ett kort om man inte känner till beloppet?

https://medlem.io/profile/payments [tom sida]

Kanske borde det stå nåt typ "inga betalningsalternativ registrerade, var vänlig välj en produkt för att registrera ett betalningsalternativ"

**Comment by Hanifb** [comment]
Fixat, tack!
