### ISSUE TITLE
Kort läggs till flera gånger och de går inte att ta bort

### ISSUE THREAD

**Issue by oscfor** [Hanifb/medlem.io#22]
Samma Issue som tidigare.

<img width="754" alt="image" src="https://github.com/user-attachments/assets/357c7659-fab8-4cae-a13e-57ccc83e8972">

**Comment by Hanifb** [comment]
Detta ska vara åtgärdat. Prova gärna igen @oscfor.

**Comment by Jens-Johansson** [comment]
Jag hör nog till dem som tycker detta fortfarande verkar lite icke-intuitivt. 

Jag hade nog egentligen fan velat ha en länk "ta bort" bredvid den här länken "ändra". 

Om nåt nu skulle balla ur på detta sätt, dvs att det finns två kort knutna till kontot (detta borde ju inte heller vara möjligt.. hur skulle systemet egentligen kunna veta vilket av dem som skulle debiteras).

![Screenshot - 2024-12-20 , 11_27_52](https://github.com/user-attachments/assets/027f6142-6fd7-4b11-b9a7-1b41e490250e)

**Comment by Hanifb** [comment]
Fixat!
