### ISSUE TITLE
Om man byter prenumeration får man dubbla prenumerationer

### ISSUE THREAD

**Issue by oscfor** [Hanifb/medlem.io#23]
Bytte från silver till brons. Det gick bra, även om den fastnade i bytet och jag blev tvungen att logga ut och in igen. När jag sedan bytte från brons till guld inträffade samma sak, men nu har jag två prenumerationer.

<img width="754" alt="image" src="https://github.com/user-attachments/assets/0fb8c48d-ba94-4126-926e-238c85f405da">

**Comment by oscfor** [comment]
Så här ser det ut när man försöker att byta prenumeration

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/fdfa94ca-20c4-4ba2-96a2-e0c7a68298c8">

**Comment by Hanifb** [comment]
Detta ska vara fixat nu, kan du prova igen @oscfor?

**Comment by oscfor** [comment]
Funkar bra!
