### ISSUE TITLE
Förbättringar kring lösenordsåterställning

### ISSUE THREAD

**Issue by Johansan79** [Hanifb/medlem.io#24]
- När man begär nytt lösenord framgår det inte att länk är skickad, och är man lite för snabb och glömmer vad man gjorde för en sekund sedan så är det lätt hänt att klicka en gång till.

- Presentera användarnamnet i read only läge (med rätt egenskaper) på sidan där man anger nya lösenordet så lösenordshanterare kan snappa upp det

- Kunde ej spara det nya lösenordet, kanske pga otillåtna tecken eller längd, eller felaktig länk. Det framgår inte i gränssnittet varför

- Efter byte av lösenord kan man klicka "Tillbaka till inloggning". Länken leder till 404.

**Comment by Hanifb** [comment]
Tack, detta är fixat nu.
