### ISSUE TITLE
hittade buggar och fötbätringar

### ISSUE THREAD

**Issue by ggustaff123** [Hanifb/medlem.io#3]
user: gustaf.hansson@ajgconsulting.se

vid inloggning tycker jag anvöndarvilkor ska öppnas i popup eller nytt fönster. alltid störigt att behöva backa tillbaka

vid inloggning tycker jag alltid det är smutt när man kan göra inloggning via mail. dvs att man får ett mail med en engångslänk

 när jag skriver in kortuppgifter så borde man automatiskt komma till ccv fältet efter man skriver sista siffran i Månad/år

snyggt att ha något betyg på avsnitt så man kan hitta topp-avsnitt

potentiella fel:
under rutan med texten om er podd så är det någon lång ruta under
<img width="1440" alt="Skärmavbild 2024-11-27 kl  19 28 45" src="https://github.com/user-attachments/assets/02871dd0-3097-4407-ab9d-d68432621ac7">

jag tror jag fick en konstig grej men hinner inte labba med det
1. jag la till kort
2.kom till en sida för att bekräfta uppgifter. skulle då få ett sms. eller "link" till email som det stod
3. backade tillbaka
4. fyllde i kort igen
5. ombads inte bekräfta numret igen

- händer inget när jag försöker skicka en kommentar till ett avsnitt. trycker på knappen skicka men ignet händer

- Jag verkar inte kunna byta mail adress.

- när jag försöker uppgradera mitt medlemskap till ett större paket och trycker bekräfta står knappen bara och snurrar

<img width="1440" alt="Skärmavbild 2024-11-27 kl  19 37 18" src="https://github.com/user-attachments/assets/bb7530e9-80e9-4643-9430-a57ac7d1b712">

Hinner inte testa mer nu
//allt gott!

**Comment by Hanifb** [comment]
Fixat buggarna, sparar förslagen på förbättringar!
