### ISSUE TITLE
Det går inte att ta bort kort och kort läggs till flera gånger

### ISSUE THREAD

**Issue by oscfor** [Hanifb/medlem.io#4]
Råkade lägga till ett kort via Apple Pay. Det finns inget sätt att ta bort det. Man möts bara av en skärm för att lägga till kort:
![IMG_6046](https://github.com/user-attachments/assets/d3dab1e3-decf-4e5d-b628-28d07939c34d)

Klickar man på Spara kort läggs ett kort till igen.

![image](https://github.com/user-attachments/assets/bbc516bd-4982-47fe-9dee-2c62d55b8a9d)

**Comment by Hanifb** [comment]
fixat
