### ISSUE TITLE
[FIXAD] Glömt lösenord ger tom sida

### ISSUE THREAD

**Issue by adde-codr** [Hanifb/medlem.io#6]
Klick på glömt lösenord leder till en sidan utan innehåll.
![IMG_2435](https://github.com/user-attachments/assets/c102bb1f-35c1-4601-807b-673f167d4c95)

**Comment by gurr0** [comment]
Jag upptäckte samma. 

Vet inte om det här är en bugg egentligen men när jag skulle logga in efter aktiveringen och tryckte på Glömt lösenordet så kom jag till samma tomma skärm. Men när jag gick in på menyn så var jag plötsligt inloggad. Jag lyckas inte återupprepa det dock. Kanske jag blev inloggad vid aktiveringen?

Jag hade förresten glömt lösen på riktigt, glömde kopiera det genererade passet och det sparades inte av Lösenord. 

Jag är tyvärr osäker men det borde ha varit via Chrome (senaste uppdateringen och senaste iOS, 27/11-24) eftersom jag kom dit via aktiveringslänken i mailet. Skulle dock kunnat vara genom att jag besökte länken i Messengerappen… 

sorry, min första buggrapport är rätt kass och ev inte en bugg. Men det blev iaf många ord!

![IMG_0766](https://github.com/user-attachments/assets/7638e6ed-8454-416d-a6e9-6296c1280ff5)
![IMG_0767](https://github.com/user-attachments/assets/813c3f5f-15f8-4360-9c6e-8d4a3b059bbe)

**Comment by Hanifb** [comment]
Tack, var en felaktig länk. Åtgärdat, kommer pushas upp senare inatt.
