### ISSUE TITLE
Betalning

### ISSUE THREAD

**Issue by davidigra** [Hanifb/medlem.io#8]
Försöker bli silvermedlem via iPhone. 

När man kommit till den del där man ska spara sitt kort för att godkänna betalning så hamnar man i en loop. Jag kommer inte vidare utan kan klicka på den gröna knappen där det står Save card hur många gånger som helst.

Kommer inte längre än så tyvärr. 

Har bifogat en liten skärminspelning kring det hela. 

https://github.com/user-attachments/assets/b8b1440e-54de-43e5-9cb1-7de8dd66758e

**Comment by DavidBoman** [comment]
+1

**Comment by Hanifb** [comment]
fixat! Tack för hjälpen!
